// Code generated by command: go run conversion_avo_amd64.go -out conversion_avo_amd64.s -stubs stub_windows.go. DO NOT EDIT.

package dsp

// Ui8tof32 converts unsigned 8-bit samples to 32-bit float.
func Ui8tof32(input []byte, output []float32)
