//go:build amd64

package encoding

// The generated assembly, used whenever the archsimd implementation in
// conversion_simd_amd64.go is unavailable: builds without GOEXPERIMENT=simd
// (the default) and CPUs without AVX, which archsimd (VEX-encoded even for
// 128-bit vectors) cannot target. See simdWidth.
//
// Dispatch is here rather than in the assembly so tests can drive each path
// directly; the leaves are generated by conversion_avo_amd64.go.

func u8ToF32Asm(dst []float32, src []byte) {
	if useSSE4 {
		u8ToF32SSE4(dst, src)
		return
	}
	u8ToF32SSE2(dst, src)
}
