// Code generated by command: go run conversion_avo_amd64.go -out conversion_avo_amd64.s -stubs conversion_avo_stub_amd64.go. DO NOT EDIT.

//go:build amd64

package encoding

// u8ToF32SSE4 converts unsigned 8-bit samples to 32-bit float using SSE4.1.
func u8ToF32SSE4(dst []float32, src []byte)

// u8ToF32SSE2 converts unsigned 8-bit samples to 32-bit float using SSE2.
func u8ToF32SSE2(dst []float32, src []byte)
