// Code generated by command: go run conversion_avo_amd64.go -out conversion_avo_amd64.s -stubs conversion_avo_stub_amd64.go. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

// func u8ToF32SSE4(dst []float32, src []byte)
// Requires: SSE, SSE2, SSE4.1
TEXT ·u8ToF32SSE4(SB), NOSPLIT, $0-48
	MOVQ src_base+24(FP), AX
	MOVQ src_len+32(FP), CX
	MOVQ dst_base+0(FP), DX
	MOVQ dst_len+8(FP), BX

	// Pick shortest length
	CMPQ BX, CX
	JGE  u8tof32_min_len
	MOVQ BX, CX

u8tof32_min_len:
	MOVQ $0x0000000000000000, BX

	// If src is too short to optimize (less than 32 bytes) then single step
	MOVQ $0x0000000000000020, SI
	CMPQ SI, CX
	JGE  u8tof32_stepper

	// Align dst to 16-byte boundary
	MOVQ DX, SI
	ANDQ $0x0f, SI
	SHRQ $0x02, SI
	JZ   u8tof32_aligned

	// t64 is how many 32-bit slots dst already sits past a boundary, so 4-t64 is how many to step first
	MOVQ $0x0000000000000004, DI
	SUBQ SI, DI

u8tof32_align:
	MOVBQZX  (AX), SI
	INCQ     AX
	SUBQ     $0x80, SI
	CVTSQ2SS SI, X0
	MOVSS    X0, (DX)
	ADDQ     $0x04, DX
	INCQ     BX
	CMPQ     BX, DI
	JLT      u8tof32_align

u8tof32_aligned:
	// Bound the blocks relative to the index the prologue left behind, not absolutely: an absolute len&^15 lets the last block start up to 15 elements short of the end and run 15 past it
	MOVQ   CX, SI
	SUBQ   BX, SI
	ANDQ   $0xfffffff0, SI
	ADDQ   BX, SI
	CMPQ   BX, SI
	JGE    u8tof32_stepper
	MOVL   $0x80808080, DI
	MOVD   DI, X3
	PSHUFL $0x00, X3, X3

u8tof32_sse4_loop:
	// Load 16 unsigned 8-bit values
	MOVOU (AX), X0

	// Make the values signed
	PSUBB X3, X0

	// Lowest 4 values (bytes 0-3)
	PMOVSXBD X0, X2

	// Convert 32-bit signed integers to 32-bit float
	CVTPL2PS X2, X2
	MOVAPS   X2, (DX)

	// Next 4 values (bytes 4-7)
	PSHUFL   $0x01, X0, X2
	PMOVSXBD X2, X2

	// Convert 32-bit signed integers to 32-bit float
	CVTPL2PS X2, X2
	MOVAPS   X2, 16(DX)

	// Next 4 values (bytes 8-11)
	PSHUFL   $0x02, X0, X2
	PMOVSXBD X2, X2

	// Convert 32-bit signed integers to 32-bit float
	CVTPL2PS X2, X2
	MOVAPS   X2, 32(DX)

	// Next 4 values (bytes 12-15)
	PSHUFL   $0x03, X0, X2
	PMOVSXBD X2, X2

	// Convert 32-bit signed integers to 32-bit float
	CVTPL2PS X2, X2
	MOVAPS   X2, 48(DX)
	ADDQ     $0x10, BX
	ADDQ     $0x10, AX
	ADDQ     $0x40, DX
	CMPQ     BX, SI
	JLT      u8tof32_sse4_loop

	// TODO: work increasingly smaller blocks
u8tof32_stepper:
	CMPQ BX, CX
	JGE  u8tof32_done

u8tof32_step:
	MOVBQZX  (AX), SI
	INCQ     AX
	SUBQ     $0x80, SI
	CVTSQ2SS SI, X1
	MOVSS    X1, (DX)
	ADDQ     $0x04, DX
	INCQ     BX
	CMPQ     BX, CX
	JLT      u8tof32_step

u8tof32_done:
	RET

// func u8ToF32SSE2(dst []float32, src []byte)
// Requires: SSE, SSE2
TEXT ·u8ToF32SSE2(SB), NOSPLIT, $0-48
	MOVQ src_base+24(FP), AX
	MOVQ src_len+32(FP), CX
	MOVQ dst_base+0(FP), DX
	MOVQ dst_len+8(FP), BX

	// Pick shortest length
	CMPQ BX, CX
	JGE  u8tof32_min_len
	MOVQ BX, CX

u8tof32_min_len:
	MOVQ $0x0000000000000000, BX

	// If src is too short to optimize (less than 32 bytes) then single step
	MOVQ $0x0000000000000020, SI
	CMPQ SI, CX
	JGE  u8tof32_stepper

	// Align dst to 16-byte boundary
	MOVQ DX, SI
	ANDQ $0x0f, SI
	SHRQ $0x02, SI
	JZ   u8tof32_aligned

	// t64 is how many 32-bit slots dst already sits past a boundary, so 4-t64 is how many to step first
	MOVQ $0x0000000000000004, DI
	SUBQ SI, DI

u8tof32_align:
	MOVBQZX  (AX), SI
	INCQ     AX
	SUBQ     $0x80, SI
	CVTSQ2SS SI, X0
	MOVSS    X0, (DX)
	ADDQ     $0x04, DX
	INCQ     BX
	CMPQ     BX, DI
	JLT      u8tof32_align

u8tof32_aligned:
	// Bound the blocks relative to the index the prologue left behind, not absolutely: an absolute len&^15 lets the last block start up to 15 elements short of the end and run 15 past it
	MOVQ   CX, SI
	SUBQ   BX, SI
	ANDQ   $0xfffffff0, SI
	ADDQ   BX, SI
	CMPQ   BX, SI
	JGE    u8tof32_stepper
	MOVL   $0x80808080, DI
	MOVD   DI, X4
	PSHUFL $0x00, X4, X4

u8tof32_sse2_loop:
	// Load 16 unsigned 8-bit values
	MOVOU (AX), X0

	// Make the values signed
	PSUBB X4, X0
	MOVO  X0, X2

	// Lowest 4 values (bytes 0-3)
	PUNPCKLBW X2, X2
	MOVO      X2, X3
	PUNPCKLWL X2, X2
	PSRAL     $0x18, X2
	CVTPL2PS  X2, X2
	MOVAPS    X2, (DX)

	// Next 4 values (bytes 4-7)
	PUNPCKHWL X3, X3
	PSRAL     $0x18, X3
	CVTPL2PS  X3, X3
	MOVAPS    X3, 16(DX)

	// Next 4 values (bytes 8-11)
	PUNPCKHBW X0, X0
	MOVO      X0, X3
	PUNPCKLWL X0, X0
	PSRAL     $0x18, X0
	CVTPL2PS  X0, X0
	MOVAPS    X0, 32(DX)

	// Next 4 values (bytes 12-15)
	PUNPCKHWL X3, X3
	PSRAL     $0x18, X3
	CVTPL2PS  X3, X3
	MOVAPS    X3, 48(DX)
	ADDQ      $0x10, BX
	ADDQ      $0x10, AX
	ADDQ      $0x40, DX
	CMPQ      BX, SI
	JLT       u8tof32_sse2_loop

	// TODO: work increasingly smaller blocks
u8tof32_stepper:
	CMPQ BX, CX
	JGE  u8tof32_done

u8tof32_step:
	MOVBQZX  (AX), SI
	INCQ     AX
	SUBQ     $0x80, SI
	CVTSQ2SS SI, X1
	MOVSS    X1, (DX)
	ADDQ     $0x04, DX
	INCQ     BX
	CMPQ     BX, CX
	JLT      u8tof32_step

u8tof32_done:
	RET
