// Code generated by command: go run math32_avo_amd64.go -out math32_asm_amd64.s -stubs math32_asm_stub_amd64.go. DO NOT EDIT.

//go:build amd64

package f32

// vscaleF32AVX calculates dst[i] = src[i] * scale using AVX.
func vscaleF32AVX(dst []float32, src []float32, scale float32)

// vscaleF32SSE2 calculates dst[i] = src[i] * scale using SSE2.
func vscaleF32SSE2(dst []float32, src []float32, scale float32)

// vmaxF32AVX returns the maximum value of src using AVX.
func vmaxF32AVX(src []float32) float32

// vmaxF32SSE2 returns the maximum value of src using SSE2.
func vmaxF32SSE2(src []float32) float32

// vminF32AVX returns the minimum value of src using AVX.
func vminF32AVX(src []float32) float32

// vminF32SSE2 returns the minimum value of src using SSE2.
func vminF32SSE2(src []float32) float32

// vabsC64AVX calculates dst[i] = |src[i]| using AVX.
func vabsC64AVX(dst []float32, src []complex64)

// vabsC64SSE2 calculates dst[i] = |src[i]| using SSE2.
func vabsC64SSE2(dst []float32, src []complex64)
