// Code generated by command: go run math32_avo_amd64.go -out math32_asm_amd64.s -stubs math32_asm_stub_amd64.go. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

// func vscaleF32AVX(dst []float32, src []float32, scale float32)
// Requires: AVX, CMOV, SSE
TEXT ·vscaleF32AVX(SB), NOSPLIT, $0-52
	MOVQ src_base+24(FP), AX
	MOVQ src_len+32(FP), CX
	MOVQ dst_base+0(FP), DX
	MOVQ dst_len+8(FP), BX

	// Process min(len(src), len(dst)) elements
	CMPQ         BX, CX
	CMOVQLT      BX, CX
	MOVSS        scale+48(FP), X0
	VBROADCASTSS scale+48(FP), Y1
	XORQ         BX, BX
	MOVQ         CX, SI
	ANDQ         $-32, SI

vector:
	CMPQ    BX, SI
	JGE     vector1
	VMULPS  (AX)(BX*4), Y1, Y2
	VMOVUPS Y2, (DX)(BX*4)
	VMULPS  32(AX)(BX*4), Y1, Y2
	VMOVUPS Y2, 32(DX)(BX*4)
	VMULPS  64(AX)(BX*4), Y1, Y2
	VMOVUPS Y2, 64(DX)(BX*4)
	VMULPS  96(AX)(BX*4), Y1, Y2
	VMOVUPS Y2, 96(DX)(BX*4)
	ADDQ    $0x00000020, BX
	JMP     vector

	// One vector at a time, so the scalar tail is at most lanes-1 wide
vector1:
	MOVQ CX, SI
	ANDQ $-8, SI

vector1loop:
	CMPQ    BX, SI
	JGE     tail
	VMULPS  (AX)(BX*4), Y1, Y2
	VMOVUPS Y2, (DX)(BX*4)
	ADDQ    $0x00000008, BX
	JMP     vector1loop

tail:
	CMPQ  BX, CX
	JGE   done
	MOVSS (AX)(BX*4), X1
	MULSS X0, X1
	MOVSS X1, (DX)(BX*4)
	INCQ  BX
	JMP   tail

done:
	VZEROUPPER
	RET

// func vscaleF32SSE2(dst []float32, src []float32, scale float32)
// Requires: CMOV, SSE
TEXT ·vscaleF32SSE2(SB), NOSPLIT, $0-52
	MOVQ src_base+24(FP), AX
	MOVQ src_len+32(FP), CX
	MOVQ dst_base+0(FP), DX
	MOVQ dst_len+8(FP), BX

	// Process min(len(src), len(dst)) elements
	CMPQ    BX, CX
	CMOVQLT BX, CX
	MOVSS   scale+48(FP), X0
	MOVSS   scale+48(FP), X1
	SHUFPS  $0x00, X1, X1
	XORQ    BX, BX
	MOVQ    CX, SI
	ANDQ    $-16, SI

vector:
	CMPQ   BX, SI
	JGE    vector1
	MOVUPS (AX)(BX*4), X2
	MULPS  X1, X2
	MOVUPS X2, (DX)(BX*4)
	MOVUPS 16(AX)(BX*4), X2
	MULPS  X1, X2
	MOVUPS X2, 16(DX)(BX*4)
	MOVUPS 32(AX)(BX*4), X2
	MULPS  X1, X2
	MOVUPS X2, 32(DX)(BX*4)
	MOVUPS 48(AX)(BX*4), X2
	MULPS  X1, X2
	MOVUPS X2, 48(DX)(BX*4)
	ADDQ   $0x00000010, BX
	JMP    vector

	// One vector at a time, so the scalar tail is at most lanes-1 wide
vector1:
	MOVQ CX, SI
	ANDQ $-4, SI

vector1loop:
	CMPQ   BX, SI
	JGE    tail
	MOVUPS (AX)(BX*4), X2
	MULPS  X1, X2
	MOVUPS X2, (DX)(BX*4)
	ADDQ   $0x00000004, BX
	JMP    vector1loop

tail:
	CMPQ  BX, CX
	JGE   done
	MOVSS (AX)(BX*4), X1
	MULSS X0, X1
	MOVSS X1, (DX)(BX*4)
	INCQ  BX
	JMP   tail

done:
	RET

DATA negInfF32<>+0(SB)/4, $0xff800000
GLOBL negInfF32<>(SB), RODATA|NOPTR, $4

DATA posInfF32<>+0(SB)/4, $0x7f800000
GLOBL posInfF32<>(SB), RODATA|NOPTR, $4

// func vmaxF32AVX(src []float32) float32
// Requires: AVX, SSE
TEXT ·vmaxF32AVX(SB), NOSPLIT, $0-28
	MOVQ         src_base+0(FP), AX
	MOVQ         src_len+8(FP), CX
	VBROADCASTSS negInfF32<>+0(SB), Y0
	VBROADCASTSS negInfF32<>+0(SB), Y1
	VBROADCASTSS negInfF32<>+0(SB), Y2
	VBROADCASTSS negInfF32<>+0(SB), Y3
	XORQ         DX, DX
	MOVQ         CX, BX
	ANDQ         $-32, BX

vector:
	CMPQ   DX, BX
	JGE    vector1
	VMAXPS (AX)(DX*4), Y0, Y0
	VMAXPS 32(AX)(DX*4), Y1, Y1
	VMAXPS 64(AX)(DX*4), Y2, Y2
	VMAXPS 96(AX)(DX*4), Y3, Y3
	ADDQ   $0x00000020, DX
	JMP    vector

	// One vector at a time, so the scalar tail is at most lanes-1 wide
vector1:
	MOVQ CX, BX
	ANDQ $-8, BX

vector1loop:
	CMPQ   DX, BX
	JGE    reduce
	VMAXPS (AX)(DX*4), Y0, Y0
	ADDQ   $0x00000008, DX
	JMP    vector1loop

reduce:
	VMAXPS       Y1, Y0, Y0
	VMAXPS       Y2, Y0, Y0
	VMAXPS       Y3, Y0, Y0
	VEXTRACTF128 $0x01, Y0, X1
	VMAXPS       X1, X0, X0
	MOVHLPS      X0, X4
	MAXPS        X4, X0
	MOVAPS       X0, X1
	SHUFPS       $0x55, X1, X1
	MAXPS        X1, X0

tail:
	CMPQ   DX, CX
	JGE    done
	MOVSS  (AX)(DX*4), X1
	MAXSS  X0, X1
	MOVAPS X1, X0
	INCQ   DX
	JMP    tail

done:
	VZEROUPPER
	MOVSS X0, ret+24(FP)
	RET

// func vmaxF32SSE2(src []float32) float32
// Requires: SSE
TEXT ·vmaxF32SSE2(SB), NOSPLIT, $0-28
	MOVQ   src_base+0(FP), AX
	MOVQ   src_len+8(FP), CX
	MOVSS  negInfF32<>+0(SB), X0
	SHUFPS $0x00, X0, X0
	MOVSS  negInfF32<>+0(SB), X1
	SHUFPS $0x00, X1, X1
	MOVSS  negInfF32<>+0(SB), X2
	SHUFPS $0x00, X2, X2
	MOVSS  negInfF32<>+0(SB), X3
	SHUFPS $0x00, X3, X3
	XORQ   DX, DX
	MOVQ   CX, BX
	ANDQ   $-16, BX

vector:
	CMPQ   DX, BX
	JGE    vector1
	MOVUPS (AX)(DX*4), X4
	MAXPS  X4, X0
	MOVUPS 16(AX)(DX*4), X4
	MAXPS  X4, X1
	MOVUPS 32(AX)(DX*4), X4
	MAXPS  X4, X2
	MOVUPS 48(AX)(DX*4), X4
	MAXPS  X4, X3
	ADDQ   $0x00000010, DX
	JMP    vector

	// One vector at a time, so the scalar tail is at most lanes-1 wide
vector1:
	MOVQ CX, BX
	ANDQ $-4, BX

vector1loop:
	CMPQ   DX, BX
	JGE    reduce
	MOVUPS (AX)(DX*4), X4
	MAXPS  X4, X0
	ADDQ   $0x00000004, DX
	JMP    vector1loop

reduce:
	MAXPS   X1, X0
	MAXPS   X2, X0
	MAXPS   X3, X0
	MOVHLPS X0, X5
	MAXPS   X5, X0
	MOVAPS  X0, X1
	SHUFPS  $0x55, X1, X1
	MAXPS   X1, X0

tail:
	CMPQ   DX, CX
	JGE    done
	MOVSS  (AX)(DX*4), X1
	MAXSS  X0, X1
	MOVAPS X1, X0
	INCQ   DX
	JMP    tail

done:
	MOVSS X0, ret+24(FP)
	RET

// func vminF32AVX(src []float32) float32
// Requires: AVX, SSE
TEXT ·vminF32AVX(SB), NOSPLIT, $0-28
	MOVQ         src_base+0(FP), AX
	MOVQ         src_len+8(FP), CX
	VBROADCASTSS posInfF32<>+0(SB), Y0
	VBROADCASTSS posInfF32<>+0(SB), Y1
	VBROADCASTSS posInfF32<>+0(SB), Y2
	VBROADCASTSS posInfF32<>+0(SB), Y3
	XORQ         DX, DX
	MOVQ         CX, BX
	ANDQ         $-32, BX

vector:
	CMPQ   DX, BX
	JGE    vector1
	VMINPS (AX)(DX*4), Y0, Y0
	VMINPS 32(AX)(DX*4), Y1, Y1
	VMINPS 64(AX)(DX*4), Y2, Y2
	VMINPS 96(AX)(DX*4), Y3, Y3
	ADDQ   $0x00000020, DX
	JMP    vector

	// One vector at a time, so the scalar tail is at most lanes-1 wide
vector1:
	MOVQ CX, BX
	ANDQ $-8, BX

vector1loop:
	CMPQ   DX, BX
	JGE    reduce
	VMINPS (AX)(DX*4), Y0, Y0
	ADDQ   $0x00000008, DX
	JMP    vector1loop

reduce:
	VMINPS       Y1, Y0, Y0
	VMINPS       Y2, Y0, Y0
	VMINPS       Y3, Y0, Y0
	VEXTRACTF128 $0x01, Y0, X1
	VMINPS       X1, X0, X0
	MOVHLPS      X0, X4
	MINPS        X4, X0
	MOVAPS       X0, X1
	SHUFPS       $0x55, X1, X1
	MINPS        X1, X0

tail:
	CMPQ   DX, CX
	JGE    done
	MOVSS  (AX)(DX*4), X1
	MINSS  X0, X1
	MOVAPS X1, X0
	INCQ   DX
	JMP    tail

done:
	VZEROUPPER
	MOVSS X0, ret+24(FP)
	RET

// func vminF32SSE2(src []float32) float32
// Requires: SSE
TEXT ·vminF32SSE2(SB), NOSPLIT, $0-28
	MOVQ   src_base+0(FP), AX
	MOVQ   src_len+8(FP), CX
	MOVSS  posInfF32<>+0(SB), X0
	SHUFPS $0x00, X0, X0
	MOVSS  posInfF32<>+0(SB), X1
	SHUFPS $0x00, X1, X1
	MOVSS  posInfF32<>+0(SB), X2
	SHUFPS $0x00, X2, X2
	MOVSS  posInfF32<>+0(SB), X3
	SHUFPS $0x00, X3, X3
	XORQ   DX, DX
	MOVQ   CX, BX
	ANDQ   $-16, BX

vector:
	CMPQ   DX, BX
	JGE    vector1
	MOVUPS (AX)(DX*4), X4
	MINPS  X4, X0
	MOVUPS 16(AX)(DX*4), X4
	MINPS  X4, X1
	MOVUPS 32(AX)(DX*4), X4
	MINPS  X4, X2
	MOVUPS 48(AX)(DX*4), X4
	MINPS  X4, X3
	ADDQ   $0x00000010, DX
	JMP    vector

	// One vector at a time, so the scalar tail is at most lanes-1 wide
vector1:
	MOVQ CX, BX
	ANDQ $-4, BX

vector1loop:
	CMPQ   DX, BX
	JGE    reduce
	MOVUPS (AX)(DX*4), X4
	MINPS  X4, X0
	ADDQ   $0x00000004, DX
	JMP    vector1loop

reduce:
	MINPS   X1, X0
	MINPS   X2, X0
	MINPS   X3, X0
	MOVHLPS X0, X5
	MINPS   X5, X0
	MOVAPS  X0, X1
	SHUFPS  $0x55, X1, X1
	MINPS   X1, X0

tail:
	CMPQ   DX, CX
	JGE    done
	MOVSS  (AX)(DX*4), X1
	MINSS  X0, X1
	MOVAPS X1, X0
	INCQ   DX
	JMP    tail

done:
	MOVSS X0, ret+24(FP)
	RET

// func vabsC64AVX(dst []float32, src []complex64)
// Requires: AVX, CMOV, SSE
TEXT ·vabsC64AVX(SB), NOSPLIT, $0-48
	MOVQ src_base+24(FP), AX
	MOVQ src_len+32(FP), CX
	MOVQ dst_base+0(FP), DX
	MOVQ dst_len+8(FP), BX

	// Process min(len(src), len(dst)) complex values
	CMPQ    BX, CX
	CMOVQLT BX, CX
	XORQ    BX, BX
	MOVQ    CX, SI
	ANDQ    $-32, SI

vector:
	CMPQ       BX, SI
	JGE        vector1
	VMOVUPS    (AX)(BX*8), Y0
	VMOVUPS    32(AX)(BX*8), Y1
	VPERM2F128 $0x20, Y1, Y0, Y2
	VPERM2F128 $0x31, Y1, Y0, Y0
	VSHUFPS    $0x88, Y0, Y2, Y1
	VSHUFPS    $0xdd, Y0, Y2, Y0
	VMULPS     Y1, Y1, Y1
	VMULPS     Y0, Y0, Y0
	VADDPS     Y0, Y1, Y1
	VSQRTPS    Y1, Y1
	VMOVUPS    Y1, (DX)(BX*4)
	VMOVUPS    64(AX)(BX*8), Y0
	VMOVUPS    96(AX)(BX*8), Y1
	VPERM2F128 $0x20, Y1, Y0, Y2
	VPERM2F128 $0x31, Y1, Y0, Y0
	VSHUFPS    $0x88, Y0, Y2, Y1
	VSHUFPS    $0xdd, Y0, Y2, Y0
	VMULPS     Y1, Y1, Y1
	VMULPS     Y0, Y0, Y0
	VADDPS     Y0, Y1, Y1
	VSQRTPS    Y1, Y1
	VMOVUPS    Y1, 32(DX)(BX*4)
	VMOVUPS    128(AX)(BX*8), Y0
	VMOVUPS    160(AX)(BX*8), Y1
	VPERM2F128 $0x20, Y1, Y0, Y2
	VPERM2F128 $0x31, Y1, Y0, Y0
	VSHUFPS    $0x88, Y0, Y2, Y1
	VSHUFPS    $0xdd, Y0, Y2, Y0
	VMULPS     Y1, Y1, Y1
	VMULPS     Y0, Y0, Y0
	VADDPS     Y0, Y1, Y1
	VSQRTPS    Y1, Y1
	VMOVUPS    Y1, 64(DX)(BX*4)
	VMOVUPS    192(AX)(BX*8), Y0
	VMOVUPS    224(AX)(BX*8), Y1
	VPERM2F128 $0x20, Y1, Y0, Y2
	VPERM2F128 $0x31, Y1, Y0, Y0
	VSHUFPS    $0x88, Y0, Y2, Y1
	VSHUFPS    $0xdd, Y0, Y2, Y0
	VMULPS     Y1, Y1, Y1
	VMULPS     Y0, Y0, Y0
	VADDPS     Y0, Y1, Y1
	VSQRTPS    Y1, Y1
	VMOVUPS    Y1, 96(DX)(BX*4)
	ADDQ       $0x00000020, BX
	JMP        vector

	// One vector at a time, so the scalar tail is at most lanes-1 wide
vector1:
	MOVQ CX, SI
	ANDQ $-8, SI

vector1loop:
	CMPQ       BX, SI
	JGE        tail
	VMOVUPS    (AX)(BX*8), Y0
	VMOVUPS    32(AX)(BX*8), Y1
	VPERM2F128 $0x20, Y1, Y0, Y2
	VPERM2F128 $0x31, Y1, Y0, Y0
	VSHUFPS    $0x88, Y0, Y2, Y1
	VSHUFPS    $0xdd, Y0, Y2, Y0
	VMULPS     Y1, Y1, Y1
	VMULPS     Y0, Y0, Y0
	VADDPS     Y0, Y1, Y1
	VSQRTPS    Y1, Y1
	VMOVUPS    Y1, (DX)(BX*4)
	ADDQ       $0x00000008, BX
	JMP        vector1loop

	// Recompute the last full vector rather than looping over the remainder
tail:
	CMPQ       BX, CX
	JGE        done
	CMPQ       CX, $0x00000008
	JL         scalar
	SUBQ       $0x00000008, CX
	VMOVUPS    (AX)(CX*8), Y0
	VMOVUPS    32(AX)(CX*8), Y1
	VPERM2F128 $0x20, Y1, Y0, Y2
	VPERM2F128 $0x31, Y1, Y0, Y0
	VSHUFPS    $0x88, Y0, Y2, Y1
	VSHUFPS    $0xdd, Y0, Y2, Y0
	VMULPS     Y1, Y1, Y1
	VMULPS     Y0, Y0, Y0
	VADDPS     Y0, Y1, Y1
	VSQRTPS    Y1, Y1
	VMOVUPS    Y1, (DX)(CX*4)
	JMP        done

	// Fewer elements than one vector: one complex value at a time
scalar:
	CMPQ   BX, CX
	JGE    done
	MOVSS  (AX)(BX*8), X0
	MOVSS  4(AX)(BX*8), X1
	MULSS  X0, X0
	MULSS  X1, X1
	ADDSS  X1, X0
	SQRTSS X0, X0
	MOVSS  X0, (DX)(BX*4)
	INCQ   BX
	JMP    scalar

done:
	VZEROUPPER
	RET

// func vabsC64SSE2(dst []float32, src []complex64)
// Requires: CMOV, SSE
TEXT ·vabsC64SSE2(SB), NOSPLIT, $0-48
	MOVQ src_base+24(FP), AX
	MOVQ src_len+32(FP), CX
	MOVQ dst_base+0(FP), DX
	MOVQ dst_len+8(FP), BX

	// Process min(len(src), len(dst)) complex values
	CMPQ    BX, CX
	CMOVQLT BX, CX
	XORQ    BX, BX
	MOVQ    CX, SI
	ANDQ    $-16, SI

vector:
	CMPQ   BX, SI
	JGE    vector1
	MOVUPS (AX)(BX*8), X0
	MOVUPS 16(AX)(BX*8), X1
	MOVAPS X0, X2
	SHUFPS $0x88, X1, X2
	MOVAPS X0, X0
	SHUFPS $0xdd, X1, X0
	MULPS  X2, X2
	MULPS  X0, X0
	ADDPS  X0, X2
	SQRTPS X2, X2
	MOVUPS X2, (DX)(BX*4)
	MOVUPS 32(AX)(BX*8), X0
	MOVUPS 48(AX)(BX*8), X1
	MOVAPS X0, X2
	SHUFPS $0x88, X1, X2
	MOVAPS X0, X0
	SHUFPS $0xdd, X1, X0
	MULPS  X2, X2
	MULPS  X0, X0
	ADDPS  X0, X2
	SQRTPS X2, X2
	MOVUPS X2, 16(DX)(BX*4)
	MOVUPS 64(AX)(BX*8), X0
	MOVUPS 80(AX)(BX*8), X1
	MOVAPS X0, X2
	SHUFPS $0x88, X1, X2
	MOVAPS X0, X0
	SHUFPS $0xdd, X1, X0
	MULPS  X2, X2
	MULPS  X0, X0
	ADDPS  X0, X2
	SQRTPS X2, X2
	MOVUPS X2, 32(DX)(BX*4)
	MOVUPS 96(AX)(BX*8), X0
	MOVUPS 112(AX)(BX*8), X1
	MOVAPS X0, X2
	SHUFPS $0x88, X1, X2
	MOVAPS X0, X0
	SHUFPS $0xdd, X1, X0
	MULPS  X2, X2
	MULPS  X0, X0
	ADDPS  X0, X2
	SQRTPS X2, X2
	MOVUPS X2, 48(DX)(BX*4)
	ADDQ   $0x00000010, BX
	JMP    vector

	// One vector at a time, so the scalar tail is at most lanes-1 wide
vector1:
	MOVQ CX, SI
	ANDQ $-4, SI

vector1loop:
	CMPQ   BX, SI
	JGE    tail
	MOVUPS (AX)(BX*8), X0
	MOVUPS 16(AX)(BX*8), X1
	MOVAPS X0, X2
	SHUFPS $0x88, X1, X2
	MOVAPS X0, X0
	SHUFPS $0xdd, X1, X0
	MULPS  X2, X2
	MULPS  X0, X0
	ADDPS  X0, X2
	SQRTPS X2, X2
	MOVUPS X2, (DX)(BX*4)
	ADDQ   $0x00000004, BX
	JMP    vector1loop

	// Recompute the last full vector rather than looping over the remainder
tail:
	CMPQ   BX, CX
	JGE    done
	CMPQ   CX, $0x00000004
	JL     scalar
	SUBQ   $0x00000004, CX
	MOVUPS (AX)(CX*8), X0
	MOVUPS 16(AX)(CX*8), X1
	MOVAPS X0, X2
	SHUFPS $0x88, X1, X2
	MOVAPS X0, X0
	SHUFPS $0xdd, X1, X0
	MULPS  X2, X2
	MULPS  X0, X0
	ADDPS  X0, X2
	SQRTPS X2, X2
	MOVUPS X2, (DX)(CX*4)
	JMP    done

	// Fewer elements than one vector: one complex value at a time
scalar:
	CMPQ   BX, CX
	JGE    done
	MOVSS  (AX)(BX*8), X0
	MOVSS  4(AX)(BX*8), X1
	MULSS  X0, X0
	MULSS  X1, X1
	ADDSS  X1, X0
	SQRTSS X0, X0
	MOVSS  X0, (DX)(BX*4)
	INCQ   BX
	JMP    scalar

done:
	RET
